/*******************************************************************************
* FILENAME: project.h
* 
* PSoC Creator  3.2
*
* DESCRIPTION:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Clock_2.h"
#include "QuadD1.h"
#include "Enc1CW.h"
#include "Enc1CW_aliases.h"
#include "Enc1CCW.h"
#include "Enc1CCW_aliases.h"
#include "Enc2CW.h"
#include "Enc2CW_aliases.h"
#include "Enc2CCW.h"
#include "Enc2CCW_aliases.h"
#include "QuadD2.h"
#include "QuadD3.h"
#include "Enc3CCW.h"
#include "Enc3CCW_aliases.h"
#include "Enc3CW.h"
#include "Enc3CW_aliases.h"
#include "QuadD4.h"
#include "Enc4CCW.h"
#include "Enc4CCW_aliases.h"
#include "Enc4CW.h"
#include "Enc4CW_aliases.h"
#include "CapSense.h"
#include "CapSense_CSHL.h"
#include "CapSense_TunerHelper.h"
#include "CapSense_SMS.h"
#include "CapSense_PVT.h"
#include "CapSense_IP.h"
#include "I2C.h"
#include "I2C_PINS.h"
#include "I2C_PVT.h"
#include "I2C_EZI2C.h"
#include "I2C_EZI2C_PVT.h"
#include "I2C_BOOT.h"
#include "Pin_1.h"
#include "Pin_1_aliases.h"
#include "Pin_2.h"
#include "Pin_2_aliases.h"
#include "CapSense_SampleClk.h"
#include "CapSense_Sns_aliases.h"
#include "CapSense_SenseClk.h"
#include "I2C_SCBCLK.h"
#include "I2C_sda.h"
#include "I2C_sda_aliases.h"
#include "I2C_scl.h"
#include "I2C_scl_aliases.h"
#include "I2C_SCB_IRQ.h"
#include "core_cm0_psoc4.h"
#include "core_cm0.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"
#include "CyDMA.h"
#include "CyLFClk.h"

/*[]*/

