// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xnco3.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XNco3_CfgInitialize(XNco3 *InstancePtr, XNco3_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

u32 XNco3_Get_sine_sample(XNco3 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XNco3_ReadReg(InstancePtr->Axilites_BaseAddress, XNCO3_AXILITES_ADDR_SINE_SAMPLE_DATA);
    return Data;
}

u32 XNco3_Get_sine_sample_vld(XNco3 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XNco3_ReadReg(InstancePtr->Axilites_BaseAddress, XNCO3_AXILITES_ADDR_SINE_SAMPLE_CTRL);
    return Data & 0x1;
}

void XNco3_Set_step_size(XNco3 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XNco3_WriteReg(InstancePtr->Axilites_BaseAddress, XNCO3_AXILITES_ADDR_STEP_SIZE_DATA, Data);
}

u32 XNco3_Get_step_size(XNco3 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XNco3_ReadReg(InstancePtr->Axilites_BaseAddress, XNCO3_AXILITES_ADDR_STEP_SIZE_DATA);
    return Data;
}

