// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xnco3.h"

extern XNco3_Config XNco3_ConfigTable[];

XNco3_Config *XNco3_LookupConfig(u16 DeviceId) {
	XNco3_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XNCO3_NUM_INSTANCES; Index++) {
		if (XNco3_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XNco3_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XNco3_Initialize(XNco3 *InstancePtr, u16 DeviceId) {
	XNco3_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XNco3_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XNco3_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

