// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XNCO3_H
#define XNCO3_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xnco3_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XNco3_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XNco3;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XNco3_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XNco3_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XNco3_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XNco3_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XNco3_Initialize(XNco3 *InstancePtr, u16 DeviceId);
XNco3_Config* XNco3_LookupConfig(u16 DeviceId);
int XNco3_CfgInitialize(XNco3 *InstancePtr, XNco3_Config *ConfigPtr);
#else
int XNco3_Initialize(XNco3 *InstancePtr, const char* InstanceName);
int XNco3_Release(XNco3 *InstancePtr);
#endif


u32 XNco3_Get_sine_sample(XNco3 *InstancePtr);
u32 XNco3_Get_sine_sample_vld(XNco3 *InstancePtr);
void XNco3_Set_step_size(XNco3 *InstancePtr, u32 Data);
u32 XNco3_Get_step_size(XNco3 *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
