// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xnco2.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XNco2_CfgInitialize(XNco2 *InstancePtr, XNco2_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XNco2_Set_freqControl(XNco2 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XNco2_WriteReg(InstancePtr->Axilites_BaseAddress, XNCO2_AXILITES_ADDR_FREQCONTROL_DATA, Data);
}

u32 XNco2_Get_freqControl(XNco2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XNco2_ReadReg(InstancePtr->Axilites_BaseAddress, XNCO2_AXILITES_ADDR_FREQCONTROL_DATA);
    return Data;
}

u32 XNco2_Get_sine_out_V(XNco2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XNco2_ReadReg(InstancePtr->Axilites_BaseAddress, XNCO2_AXILITES_ADDR_SINE_OUT_V_DATA);
    return Data;
}

u32 XNco2_Get_sine_out_V_vld(XNco2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XNco2_ReadReg(InstancePtr->Axilites_BaseAddress, XNCO2_AXILITES_ADDR_SINE_OUT_V_CTRL);
    return Data & 0x1;
}

