// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _NCO2_HH_
#define _NCO2_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "NCO2_dmul_64ns_64bkb.h"
#include "NCO2_ddiv_64ns_64cud.h"
#include "NCO2_sitodp_32ns_dEe.h"
#include "NCO2_sine_V.h"
#include "NCO2_AXILiteS_s_axi.h"

namespace ap_rtl {

template<unsigned int C_S_AXI_AXILITES_ADDR_WIDTH = 5,
         unsigned int C_S_AXI_AXILITES_DATA_WIDTH = 32>
struct NCO2 : public sc_module {
    // Port declarations 19
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_logic > s_axi_AXILiteS_AWVALID;
    sc_out< sc_logic > s_axi_AXILiteS_AWREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_ADDR_WIDTH> > s_axi_AXILiteS_AWADDR;
    sc_in< sc_logic > s_axi_AXILiteS_WVALID;
    sc_out< sc_logic > s_axi_AXILiteS_WREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH> > s_axi_AXILiteS_WDATA;
    sc_in< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH/8> > s_axi_AXILiteS_WSTRB;
    sc_in< sc_logic > s_axi_AXILiteS_ARVALID;
    sc_out< sc_logic > s_axi_AXILiteS_ARREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_ADDR_WIDTH> > s_axi_AXILiteS_ARADDR;
    sc_out< sc_logic > s_axi_AXILiteS_RVALID;
    sc_in< sc_logic > s_axi_AXILiteS_RREADY;
    sc_out< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH> > s_axi_AXILiteS_RDATA;
    sc_out< sc_lv<2> > s_axi_AXILiteS_RRESP;
    sc_out< sc_logic > s_axi_AXILiteS_BVALID;
    sc_in< sc_logic > s_axi_AXILiteS_BREADY;
    sc_out< sc_lv<2> > s_axi_AXILiteS_BRESP;
    sc_signal< sc_logic > ap_var_for_const0;
    sc_signal< sc_lv<64> > ap_var_for_const1;
    sc_signal< sc_lv<64> > ap_var_for_const2;


    // Module declarations
    NCO2(sc_module_name name);
    SC_HAS_PROCESS(NCO2);

    ~NCO2();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    NCO2_sine_V* sine_V_U;
    NCO2_AXILiteS_s_axi<C_S_AXI_AXILITES_ADDR_WIDTH,C_S_AXI_AXILITES_DATA_WIDTH>* NCO2_AXILiteS_s_axi_U;
    NCO2_dmul_64ns_64bkb<1,6,64,64,64>* NCO2_dmul_64ns_64bkb_U0;
    NCO2_ddiv_64ns_64cud<1,31,64,64,64>* NCO2_ddiv_64ns_64cud_U1;
    NCO2_sitodp_32ns_dEe<1,5,32,64>* NCO2_sitodp_32ns_dEe_U2;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_lv<32> > freqControl;
    sc_signal< sc_lv<24> > sine_out_V;
    sc_signal< sc_logic > sine_out_V_ap_vld;
    sc_signal< sc_lv<32> > accumulator_V;
    sc_signal< sc_lv<13> > sine_V_address0;
    sc_signal< sc_logic > sine_V_ce0;
    sc_signal< sc_lv<23> > sine_V_q0;
    sc_signal< sc_lv<45> > ap_CS_fsm;
    sc_signal< sc_lv<1> > ap_CS_fsm_state3;
    sc_signal< sc_lv<64> > grp_fu_107_p1;
    sc_signal< sc_lv<64> > tmp_s_reg_296;
    sc_signal< sc_lv<1> > ap_CS_fsm_state7;
    sc_signal< sc_lv<64> > grp_fu_102_p2;
    sc_signal< sc_lv<64> > tmp_1_reg_301;
    sc_signal< sc_lv<1> > ap_CS_fsm_state38;
    sc_signal< sc_lv<1> > ap_CS_fsm_state44;
    sc_signal< sc_lv<64> > grp_fu_97_p2;
    sc_signal< sc_lv<64> > val_assign_reg_311;
    sc_signal< sc_lv<32> > tmp_3_fu_139_p1;
    sc_signal< sc_lv<32> > tmp_2_fu_269_p2;
    sc_signal< sc_lv<1> > ap_CS_fsm_state45;
    sc_signal< sc_lv<13> > phitmp_fu_123_p4;
    sc_signal< sc_lv<32> > result_V_fu_255_p3;
    sc_signal< sc_lv<32> > freqControl_assign_fu_68;
    sc_signal< sc_lv<1> > ap_CS_fsm_state1;
    sc_signal< sc_lv<1> > ap_CS_fsm_state39;
    sc_signal< sc_lv<1> > ap_CS_fsm_state8;
    sc_signal< sc_lv<64> > p_Val2_s_fu_144_p1;
    sc_signal< sc_lv<52> > loc_V_1_fu_157_p1;
    sc_signal< sc_lv<53> > p_Result_s_fu_161_p3;
    sc_signal< sc_lv<11> > loc_V_fu_147_p4;
    sc_signal< sc_lv<12> > tmp_i_i_i_cast1_fu_173_p1;
    sc_signal< sc_lv<12> > sh_assign_fu_177_p2;
    sc_signal< sc_lv<11> > tmp_2_i_i_fu_191_p2;
    sc_signal< sc_lv<1> > isNeg_fu_183_p3;
    sc_signal< sc_lv<12> > tmp_2_i_i_cast_fu_197_p1;
    sc_signal< sc_lv<12> > sh_assign_1_fu_201_p3;
    sc_signal< sc_lv<32> > sh_assign_1_cast_fu_209_p1;
    sc_signal< sc_lv<53> > tmp_4_i_i_cast_fu_217_p1;
    sc_signal< sc_lv<136> > tmp_i_i_fu_169_p1;
    sc_signal< sc_lv<136> > tmp_4_i_i_fu_213_p1;
    sc_signal< sc_lv<53> > tmp_5_i_i_fu_221_p2;
    sc_signal< sc_lv<1> > tmp_fu_233_p3;
    sc_signal< sc_lv<136> > tmp_7_i_i_fu_227_p2;
    sc_signal< sc_lv<32> > tmp_4_fu_241_p1;
    sc_signal< sc_lv<32> > tmp_5_fu_245_p4;
    sc_signal< sc_lv<45> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<45> ap_ST_fsm_state1;
    static const sc_lv<45> ap_ST_fsm_state2;
    static const sc_lv<45> ap_ST_fsm_state3;
    static const sc_lv<45> ap_ST_fsm_state4;
    static const sc_lv<45> ap_ST_fsm_state5;
    static const sc_lv<45> ap_ST_fsm_state6;
    static const sc_lv<45> ap_ST_fsm_state7;
    static const sc_lv<45> ap_ST_fsm_state8;
    static const sc_lv<45> ap_ST_fsm_state9;
    static const sc_lv<45> ap_ST_fsm_state10;
    static const sc_lv<45> ap_ST_fsm_state11;
    static const sc_lv<45> ap_ST_fsm_state12;
    static const sc_lv<45> ap_ST_fsm_state13;
    static const sc_lv<45> ap_ST_fsm_state14;
    static const sc_lv<45> ap_ST_fsm_state15;
    static const sc_lv<45> ap_ST_fsm_state16;
    static const sc_lv<45> ap_ST_fsm_state17;
    static const sc_lv<45> ap_ST_fsm_state18;
    static const sc_lv<45> ap_ST_fsm_state19;
    static const sc_lv<45> ap_ST_fsm_state20;
    static const sc_lv<45> ap_ST_fsm_state21;
    static const sc_lv<45> ap_ST_fsm_state22;
    static const sc_lv<45> ap_ST_fsm_state23;
    static const sc_lv<45> ap_ST_fsm_state24;
    static const sc_lv<45> ap_ST_fsm_state25;
    static const sc_lv<45> ap_ST_fsm_state26;
    static const sc_lv<45> ap_ST_fsm_state27;
    static const sc_lv<45> ap_ST_fsm_state28;
    static const sc_lv<45> ap_ST_fsm_state29;
    static const sc_lv<45> ap_ST_fsm_state30;
    static const sc_lv<45> ap_ST_fsm_state31;
    static const sc_lv<45> ap_ST_fsm_state32;
    static const sc_lv<45> ap_ST_fsm_state33;
    static const sc_lv<45> ap_ST_fsm_state34;
    static const sc_lv<45> ap_ST_fsm_state35;
    static const sc_lv<45> ap_ST_fsm_state36;
    static const sc_lv<45> ap_ST_fsm_state37;
    static const sc_lv<45> ap_ST_fsm_state38;
    static const sc_lv<45> ap_ST_fsm_state39;
    static const sc_lv<45> ap_ST_fsm_state40;
    static const sc_lv<45> ap_ST_fsm_state41;
    static const sc_lv<45> ap_ST_fsm_state42;
    static const sc_lv<45> ap_ST_fsm_state43;
    static const sc_lv<45> ap_ST_fsm_state44;
    static const sc_lv<45> ap_ST_fsm_state45;
    static const sc_lv<32> ap_const_lv32_0;
    static const int C_S_AXI_DATA_WIDTH;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_25;
    static const sc_lv<32> ap_const_lv32_2B;
    static const sc_lv<32> ap_const_lv32_2C;
    static const sc_lv<64> ap_const_lv64_4046800000000000;
    static const sc_lv<32> ap_const_lv32_26;
    static const sc_lv<64> ap_const_lv64_3F97D6B65A9A8049;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_13;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<32> ap_const_lv32_34;
    static const sc_lv<32> ap_const_lv32_3E;
    static const sc_lv<12> ap_const_lv12_C01;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<11> ap_const_lv11_3FF;
    static const sc_lv<32> ap_const_lv32_53;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_var_for_const1();
    void thread_ap_var_for_const2();
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state38();
    void thread_ap_CS_fsm_state39();
    void thread_ap_CS_fsm_state44();
    void thread_ap_CS_fsm_state45();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_rst_n_inv();
    void thread_isNeg_fu_183_p3();
    void thread_loc_V_1_fu_157_p1();
    void thread_loc_V_fu_147_p4();
    void thread_p_Result_s_fu_161_p3();
    void thread_p_Val2_s_fu_144_p1();
    void thread_phitmp_fu_123_p4();
    void thread_result_V_fu_255_p3();
    void thread_sh_assign_1_cast_fu_209_p1();
    void thread_sh_assign_1_fu_201_p3();
    void thread_sh_assign_fu_177_p2();
    void thread_sine_V_address0();
    void thread_sine_V_ce0();
    void thread_sine_out_V();
    void thread_sine_out_V_ap_vld();
    void thread_tmp_2_fu_269_p2();
    void thread_tmp_2_i_i_cast_fu_197_p1();
    void thread_tmp_2_i_i_fu_191_p2();
    void thread_tmp_3_fu_139_p1();
    void thread_tmp_4_fu_241_p1();
    void thread_tmp_4_i_i_cast_fu_217_p1();
    void thread_tmp_4_i_i_fu_213_p1();
    void thread_tmp_5_fu_245_p4();
    void thread_tmp_5_i_i_fu_221_p2();
    void thread_tmp_7_i_i_fu_227_p2();
    void thread_tmp_fu_233_p3();
    void thread_tmp_i_i_fu_169_p1();
    void thread_tmp_i_i_i_cast1_fu_173_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
