// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xnco2.h"

extern XNco2_Config XNco2_ConfigTable[];

XNco2_Config *XNco2_LookupConfig(u16 DeviceId) {
	XNco2_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XNCO2_NUM_INSTANCES; Index++) {
		if (XNco2_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XNco2_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XNco2_Initialize(XNco2 *InstancePtr, u16 DeviceId) {
	XNco2_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XNco2_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XNco2_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

